/**
 * Blog data layer — public API.
 *
 * All data is read at build time via import.meta.glob (eager).
 * No Node built-ins are used (Cloudflare adapter compatible).
 *
 * Pure pipeline logic lives in blog-pipeline.ts (testable independently).
 */
import type { BlogPost, Category, Author } from '$lib/types/blog';
import {
	buildPostsFromGlob,
	getCategoriesFromPosts,
	getPostsByCategoryFromPosts,
	getAuthorsFromPosts,
	getPostsByAuthorFromPosts,
	getNewsPosts as getNewsPostsFromPosts,
	getArticlePosts as getArticlePostsFromPosts
} from '$lib/data/blog-pipeline';
import coverThumbsRaw from '$lib/data/cover-thumbs.json';
import postFaqsRaw from '$lib/data/post-faqs.json';

const coverThumbs = coverThumbsRaw as Record<string, { thumb: string; srcset?: string }>;
const postFaqs = postFaqsRaw as Record<string, { question: string; answer: string }[]>;

// ─── Build-time data load ─────────────────────────────────────────────────────

// Frontmatter ONLY — evaluated eagerly at build time. `import: 'metadata'` pulls just
// the exported frontmatter object from each .svx, NOT the compiled component. This keeps
// listing pages (index/category/author/sitemaps) from bundling every post body (CWV).
// Path is relative to THIS FILE (src/lib/data/blog.ts → ../content/blog/).
const metaModules = import.meta.glob('../../content/blog/*.svx', {
	eager: true,
	import: 'metadata'
}) as Record<string, unknown>;

// Compiled components — LAZY loaders, code-split per post. Only the visited post's
// body chunk is fetched (in [slug]/+page.ts via getPostComponentLoader).
const componentLoaders = import.meta.glob('../../content/blog/*.svx', {
	import: 'default'
}) as Record<string, () => Promise<unknown>>;

// Posts cache — computed once at module evaluation time (ADR-003, ADR-004).
// The date filter uses the current date at build time (ADR-004).
// Wrap each metadata value into the GlobModule shape the pure pipeline expects.
const _allPosts: BlogPost[] = buildPostsFromGlob(
	Object.fromEntries(Object.entries(metaModules).map(([path, metadata]) => [path, { metadata }]))
);

// Attach the card-sized cover variant (~768px) from the generated lookup, so listing
// grids serve a card-appropriate image instead of the full-size cover (CWV / LCP).
// Also attach FAQ pairs and cover thumbs in one pass.
for (const post of _allPosts) {
	const info = coverThumbs[post.coverImage];
	post.coverImageThumb = info?.thumb ?? post.coverImage;
	post.coverImageSrcset = info?.srcset;

	// Attach pre-extracted FAQ pairs (generated by scripts/gen-post-faqs.ts).
	const faqs = postFaqs[post.slug];
	if (faqs && faqs.length > 0) {
		post.faqs = faqs;
	}
}

// Taxonomy caches
const _categories: Category[] = getCategoriesFromPosts(_allPosts);
const _authors: Author[] = getAuthorsFromPosts(_allPosts);

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Returns all published, non-draft posts sorted by publishDate descending.
 */
export function getAllPosts(): BlogPost[] {
	return _allPosts;
}

/**
 * @deprecated Use getAllPosts() — kept for spec compatibility (SC-BC spec references getPosts()).
 */
export function getPosts(): BlogPost[] {
	return _allPosts;
}

/**
 * Returns a single post by slug, or undefined if not found.
 */
export function getPostBySlug(slug: string): BlogPost | undefined {
	return _allPosts.find((p) => p.slug === slug);
}

/**
 * @deprecated Use getPostBySlug() — kept for spec compatibility.
 */
export function getPost(slug: string): BlogPost | undefined {
	return getPostBySlug(slug);
}

/**
 * Returns all slugs of published posts (used by entries generators).
 */
export function getPostSlugs(): string[] {
	return _allPosts.map((p) => p.slug);
}

/**
 * Returns deduplicated categories derived from published posts, sorted alphabetically.
 */
export function getCategories(): Category[] {
	return _categories;
}

/**
 * Returns published posts in the given category slug.
 * Returns an empty array if the category does not exist or has no posts.
 */
export function getPostsByCategory(categorySlug: string): BlogPost[] {
	return getPostsByCategoryFromPosts(_allPosts, categorySlug);
}

/**
 * Returns deduplicated authors derived from published posts, sorted alphabetically.
 */
export function getAuthors(): Author[] {
	return _authors;
}

/**
 * Returns published posts by the given author slug.
 * Returns an empty array if the author does not exist or has no posts.
 */
export function getPostsByAuthor(authorSlug: string): BlogPost[] {
	return getPostsByAuthorFromPosts(_allPosts, authorSlug);
}

/**
 * Returns published posts in the "News" category (isNews === true).
 */
export function getNewsPosts(): BlogPost[] {
	return getNewsPostsFromPosts(_allPosts);
}

/**
 * Returns published non-news posts (isNews === false).
 */
export function getArticlePosts(): BlogPost[] {
	return getArticlePostsFromPosts(_allPosts);
}

/**
 * Returns the lazy loader for a post's compiled mdsvex component, or undefined.
 * Used by /blog/[slug]/+page.ts to fetch ONLY the visited post's body chunk.
 */
export function getPostComponentLoader(slug: string): (() => Promise<unknown>) | undefined {
	const entry = Object.entries(componentLoaders).find(
		([path]) => path.split('/').pop()?.replace(/\.svx$/, '') === slug
	);
	return entry?.[1];
}
